In [3]:
import numpy as np

1. Arrays VS Lists

In [9]:
lst = [1, 2, 3]
print(lst)
print(type(lst))
print('-----------')

arr = np.array([1, 2, 3])
print(arr)
print(type(arr))
print('-----------')

print(lst == arr)                 # Comparing elements of the array and list
print('-----------')

print(arr.tolist() == lst)        # Comparing whole list to the array which is converted into list
print('-----------')

print(sorted(arr) == sorted(lst)) # Comparing arr and lst when the elements are same but are not sorted
print('-----------')

[1, 2, 3]
<class 'list'>
----------
[1 2 3]
<class 'numpy.ndarray'>
----------
[ True  True  True]
----------
True
----------
True


2. Adding Elements in an Array and List

In [11]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lst)
lst.append(4)
print(lst)
print('-----------')

print(arr)
arr = np.append(arr, 4)
print(arr)
print('-----------')

[1, 2, 3]
[1, 2, 3, 4]
-----------
[1 2 3]
[1 2 3 4]
-----------


3. Removing Elements in an Array and List

In [14]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lst)
# lst.pop()                  # to remove an element from list (method 1)
del lst[-1]                  # to remove an element from list (method 2)
print(lst)
print('-----------')

print(arr)
arr = np.delete(arr, -2)
print(arr)
print('-----------')

[1, 2, 3]
[1, 2]
-----------
[1 2 3]
[1 3]
-----------


4. Updating Elements in an Array and List

In [17]:
lst = [1, 2, 3, 4]
print(lst)
lst[2] = 5                # to update the list (index value 2 is replaced by '5')
print(lst)
print('-----------')

arr = np.array([1, 2, 3, 4])
print(arr)
arr[2] = 5               # to update the array (index value 2 is replaced by '5')
arr[-1] = 6              # to update the array (index value -1 is replaced by '6')
print(arr)
print('-----------')

[1, 2, 3, 4]
[1, 2, 5, 4]
-----------
[1 2 3 4]
[1 2 5 6]
-----------
