In [1]:
import numpy as np

1D Array

In [2]:

np.random.seed(10)  # Setting the random seed for reproducibility

# Generating a 1D NumPy array of 10 random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=10)

print(arr)  # Printing the generated array
print('-' * 10)  # Printing a separator for better readability

# Finding the indices where the elements in the array are greater than or equal to 5
indices = np.where(arr >= 5)

# Printing the list of indices that satisfy the condition
print(list(indices[0]))
print('-' * 10)  # Printing another separator

# Printing the actual values in the array that meet the condition
print(arr[indices])

[10  5  1  2 10  1  2  9 10  1]
----------
[np.int64(0), np.int64(1), np.int64(4), np.int64(7), np.int64(8)]
----------
[10  5 10  9 10]


2D Array

In [3]:
np.random.seed(10)  # Setting the random seed for reproducibility

# Generating a 3x3 NumPy array with random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=(3, 3))

print(arr)  # Printing the generated 3x3 matrix
print('-' * 10)  # Printing a separator for better readability

# Finding the indices where the elements in the array are greater than or equal to 5
indices = np.where(arr >= 5)

# Printing the tuple of arrays containing row and column indices of elements satisfying the condition
print(indices)
print('-' * 10)  # Printing another separator

# Printing the actual values in the array that meet the condition
print(arr[indices])

[[10  5  1]
 [ 2 10  1]
 [ 2  9 10]]
----------
(array([0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2]))
----------
[10  5 10  9 10]


3D Array

In [4]:
np.random.seed(10)  # Setting the random seed for reproducibility

# Generating a 3x3x3 NumPy array with random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=(3, 3, 3))

# Printing the generated 3D array
print(arr)
print('-' * 10)  # Printing a separator for better readability

# Finding the indices where the elements in the array are greater than or equal to 5
indices = np.where(arr >= 5)

# Printing the tuple of arrays containing indices of elements satisfying the condition
# indices[0] -> first dimension (depth)
# indices[1] -> second dimension (rows)
# indices[2] -> third dimension (columns)
print(indices)
print('-' * 10)  # Printing another separator

# Printing the actual values in the array that meet the condition
print(arr[indices])

[[[10  5  1]
  [ 2 10  1]
  [ 2  9 10]]

 [[ 1  9  7]
  [ 5  4  1]
  [ 5  7  9]]

 [[ 2  9  5]
  [ 2  4  7]
  [ 6  4 10]]]
----------
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 2, 1, 2, 2, 0, 2]))
----------
[10  5 10  9 10  9  7  5  5  7  9  9  5  7  6 10]


In [5]:
np.random.seed(10)  # Setting the random seed for reproducibility

# Generating a 3x3x3 NumPy array with random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=(3, 3, 3))

# Finding the indices where the elements in the array are greater than or equal to 5
indices = np.where(arr >= 5)

# Iterating through the tuple of index arrays and printing each array separately
for i in range(len(indices)):
    print(indices[i])  # Printing the indices for each dimension

[0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2]
[0 0 1 2 2 0 0 1 2 2 2 0 0 1 2 2]
[0 1 1 1 2 1 2 0 0 1 2 1 2 2 0 2]
