In [1]:
import numpy as np

1. textfile

In [2]:
data = np.loadtxt('data.txt')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


2. npy

In [3]:
data = np.load('data.npy')
print(data)

[[1 2 3]
 [4 5 6]]


3. csv

In [4]:
data = np.loadtxt('data.csv')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


4. json

In [6]:
data = np.loadtxt('data.json', delimiter = ',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


5. yaml

In [7]:
data = np.loadtxt('data.yaml', delimiter = ',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]
