1. None to np.nan

In [1]:
import numpy as np
arr = np.array([1,2,3,None, 4,5,None])
print(arr)

arr[arr == None] = np.nan
print(arr)

[1 2 3 None 4 5 None]
[1 2 3 nan 4 5 nan]


2. Checking for Null Values

In [2]:
arr = np.array([1,2,3,np.nan, 4,5,np.nan])
print(arr)

print(np.isnan(arr))

[ 1.  2.  3. nan  4.  5. nan]
[False False False  True False False  True]


3. Removing Null Values

In [3]:
arr = np.array([1,2,3,np.nan, 4,5,np.nan])

print(np.isnan(arr))
print(~np.isnan(arr))

arr = arr[~np.isnan(arr)]
print(arr)

[False False False  True False False  True]
[ True  True  True False  True  True False]
[1. 2. 3. 4. 5.]


4. Filling Null Values with Fixed Values

In [4]:
arr = np.array([1,2,3, np.nan, 4,5,np.nan])
print(arr)

arr[np.isnan(arr)] = 0
print(arr)

[ 1.  2.  3. nan  4.  5. nan]
[1. 2. 3. 0. 4. 5. 0.]


5. Filling Null Values with Average

In [5]:
arr = np.array([21,22,22, np.nan, 24,25,np.nan])
print(arr)

arr[np.isnan(arr)] = int(np.nanmean(arr))
print(arr)

[21. 22. 22. nan 24. 25. nan]
[21. 22. 22. 22. 24. 25. 22.]
