In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,11, size = (5, 5))
arr

array([[ 9,  8,  6,  5,  9],
       [ 7,  8,  3,  6,  7],
       [ 8,  8, 10,  8,  1],
       [ 4,  9,  4,  1,  7],
       [ 5,  8,  5,  2,  6]])

1. Filtering

- Filtering elements greater than 5

In [ ]:
arr[arr>5]

array([ 9,  8,  6,  9,  7,  8,  6,  7,  8,  8, 10,  8,  9,  7,  8,  6])

- Filtering the elements that are even

In [ ]:
arr%2

array([[1, 0, 0, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 1, 1],
       [1, 0, 1, 0, 0]])

In [ ]:
arr%2 == 0

array([[False,  True,  True, False, False],
       [False,  True, False,  True, False],
       [ True,  True,  True,  True, False],
       [ True, False,  True, False, False],
       [False,  True, False,  True,  True]])

- Filter elements that are greater than 5 and are even

In [ ]:
arr[(arr>5) & (arr%2 == 0)]

array([ 8,  6,  8,  6,  8,  8, 10,  8,  8,  6])

- Filter elements that are divisible by 3 or 7

In [ ]:
arr[(arr%3 == 0) | (arr%7 == 0)]

array([9, 6, 9, 7, 3, 6, 7, 9, 7, 6])

- Filtering Based on Conditions of Another Array

In [ ]:
arr = np.random.randint(1,11,size=(5,5))
arr1 = np.array([True, False, True,False,True])
print(arr[arr1])

[[3 5 7 2 1]
 [1 4 3 4 2]
 [4 1 2 2 4]]


- Filtering Based on Specific Row Conditions

In [ ]:
arr = np.random.randint(1,11,size=(5,5))
filtered_arr = arr[2][arr[2,:] > 5]
print(filtered_arr)

[10 10  8]


2. Aggregating data

- Summation

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

15
21
[5 7 9]
[ 6 15]


- Mean Calculation

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

3.0
3.5
[2.5 3.5 4.5]
[2. 5.]


- Standard Deviation

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.std(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.std(arr))
print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

1.4142135623730951
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


- Minimum and Maximum

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.min(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))

print('-'*20)

arr = np.array([1,2,3,4,5])
print(np.max(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))

1
1
[1 2 3]
[1 4]
--------------------
5
6
[4 5 6]
[3 6]
