Searching:

In [5]:
## Linear Search:

import numpy as np
arr = np.array([1,3,4,6,5,7,12,13])
index = np.where(arr == 3)[0]
print(index)

## Binary Search

index1 = np.searchsorted(arr, 5)
print(index1)

## Searching Closest Value

index2 = np.argmin(abs(arr - 11))
print(index2)

[1]
3
6


Sorting:

In [8]:
## Quick Sort

arr = np.array([5,7,9,0,3,1,6,2,4,8])
sorted_arr = np.sort(arr)
print(sorted_arr)

## Heap Sort

sorted_arr1 = np.sort(arr, kind = 'heapsort')
print(sorted_arr1)

## Merge Sort

sorted_arr2 = np.sort(arr, kind = 'mergesort')
print(sorted_arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
