In [1]:
import numpy as np

1. CONVERTING DATA STRUCTURES TO NUMPY ARRAYS

1.1 Converting a tuple to an array

In [2]:
tpl = (1, 2, 3)
print(tpl)
print(type(tpl))
print('----------')

arr = np.array(tpl)
print(arr)
print(type(arr))
print('----------')

(1, 2, 3)
<class 'tuple'>
----------
[1 2 3]
<class 'numpy.ndarray'>
----------


1.2 Converting a list into an array

In [3]:
lst = [1, 2, 3]
print(lst)
print(type(lst))
print('----------')

arr = np.array(lst)
print(arr)
print(type(arr))
print('----------')

[1, 2, 3]
<class 'list'>
----------
[1 2 3]
<class 'numpy.ndarray'>
----------


1.3 Converting a dictionary into an array

In [7]:
dict = {1 : 'Apple', 2 : 'Banana', 3 : 'Cherry'}
print(dict)
print(type(dict))
print('----------')

arr = np.array(dict)
print(arr)
print(type(arr))
print('----------')

arr_k = np.array(list(dict.keys()))
arr_v = np.array(list(dict.values()))
print(arr_k)
print(arr_v)

{1: 'Apple', 2: 'Banana', 3: 'Cherry'}
<class 'dict'>
----------
{1: 'Apple', 2: 'Banana', 3: 'Cherry'}
<class 'numpy.ndarray'>
----------
[1 2 3]
['Apple' 'Banana' 'Cherry']


1.4 Converting a set into an array

In [13]:
set_ = {1, 2, 3}
print(set_)
print(type(set_))
print('----------')

arr = np.array(list(set_))
print(arr)
print(type(arr))

{1, 2, 3}
<class 'set'>
----------
[1 2 3]
<class 'numpy.ndarray'>


In [16]:
arr = np.array('Hello World')
arr1 = np.array(list('Hello World'))

print(arr)
print(type(arr))
print('-' * 10)

print(arr1)
print(type(arr1))

Hello World
<class 'numpy.ndarray'>
----------
['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>


2. CONVERTING THE DATATYPES OF NUMPY ARRAYS

2.1 Create an array of integers

In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[ True  True  True  True  True]


2.2 Create an array of floats

In [18]:
arr = np.array([1. , 2. , 3. , 4. , 5.])
print(arr)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
['1.0' '2.0' '3.0' '4.0' '5.0']
[ True  True  True  True  True]


2.3 Create an array of strings

In [19]:
arr = np.array(['1', '2', '3', '4', '5'])
print(arr)

arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
[1 2 3 4 5]
[ True  True  True  True  True]


2.4 Create an array of booleans

In [21]:
arr = np.array([True, False, False, False, True])
print(arr)

arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('int')
print(arr_)

[ True False False False  True]
[1. 0. 0. 0. 1.]
['True' 'False' 'False' 'False' 'True']
[1 0 0 0 1]
[ True False False False  True]
[1. 0. 0. 0. 1.]
['True' 'False' 'False' 'False' 'True']
[1 0 0 0 1]
