1. Creating Multi-dimensional Arrays:

1.1) 2D Array from a List of Lists:

In [5]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


1.2) 3D Array from a List of Lists:

In [4]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


1.3) Creating a 2D Array from a List of Tuples:

In [6]:
arr = np.array([(1, 2, 3), (4, 5, 6)])
print(arr)

[[1 2 3]
 [4 5 6]]


1.4) Creating a 3D Array from a List of Arrays:

In [7]:
arr = np.array([np.array([1,2,3]), np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


1.5) Creating a 2D Array from a List of Strings:

In [8]:
arr = np.array([['1','2','3'],['4','5','6']])
print(arr)

[['1' '2' '3']
 ['4' '5' '6']]


1.6) Creating a 2D Array from a List of Dictionaries:

In [9]:
arr = np.array([{'a' : 1, 'b' : 2, 'c' : 3},{'d' : 4, 'e' : 5, 'f' : 6}])
print(arr)

[{'a': 1, 'b': 2, 'c': 3} {'d': 4, 'e': 5, 'f': 6}]


2. Finding Details of Arrays:



2.1) Print the shape of the array

In [10]:
arr = np.array([[1,1],[4,1],[2,3]])
print(arr.shape)

(3, 2)


2.2) Printing the Number of Dimensions of the Array:

In [11]:
arr = np.array([[1,1],[4,1],[2,3]])
print(arr.ndim)

2


2.3) Printing the Data Type of the Array

In [12]:
arr = np.array([[1,1],[4,1],[2,3]])
print(arr.dtype)

int64


2.4) Printing the Size of the Array

In [16]:
arr = np.array([[1,1,2,2,3],[2,3,2,2,1]])
print(arr.size)

10


2.5) Printing the Item Size

In [15]:
arr = np.array([[1,1,2],[1,2,3],[3,2,1]])
print(arr.itemsize)

8


2.6) Printing the Type of the Array:

In [17]:
arr = np.array([[1,1,2,2],[2,3,2,1]])
print(type(arr))

<class 'numpy.ndarray'>
