In [1]:
import numpy as np

1. Copy Function with Lists:

In [2]:
lst = [1,2,3,4,5]
print(lst)
lst1 = lst
print(lst1)
print('-'*10)

lst[0] = 5
print(lst)
print(lst1)
print('-'*10)

lst1[0] = 4
print(lst)
print(lst1)

print()
print('*'*20)
print()

lst = [1,2,3,4,5]
print(lst)
lst1 = lst.copy()
print(lst1)
print('-'*10)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[5, 2, 3, 4, 5]
[5, 2, 3, 4, 5]
----------
[4, 2, 3, 4, 5]
[4, 2, 3, 4, 5]

********************

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------


2. Copy Function with Arrays:

In [3]:
arr = np.array([1,2,3,4,5])
arr_ = arr.copy()
print(arr)
print(arr_)
print('-'*10)

arr[0] = 5
print(arr)
print(arr_)
arr[0] = 1
print('-'*10)

arr_[0] = 5
print(arr)
print(arr_)

[1 2 3 4 5]
[1 2 3 4 5]
----------
[5 2 3 4 5]
[1 2 3 4 5]
----------
[1 2 3 4 5]
[5 2 3 4 5]
