In [7]:
import numpy as np

1. Indexing & Slicing with Lists

In [10]:
# Creating a Python list
my_list = [1, 2, 3, 4, 5]

# Accessing elements using positive and negative indexing
print(my_list[0])             # First element (index 0) -> Output: 1
print(my_list[-1])            # Last element (negative index -1) -> Output: 5
print(my_list[2])             # Third element (index 2) -> Output: 3

# Slicing the list
print(my_list[1:4])           # Elements from index 1 to 3 (excluding index 4) -> Output: [2, 3, 4]
print(my_list[:3])            # First 3 elements (index 0 to 2) -> Output: [1, 2, 3]
print(my_list[3:])            # Elements from index 3 to the end -> Output: [4, 5]
print(my_list[::2])           # Every second element (step=2) -> Output: [1, 3, 5]
print(my_list[::-1])          # Reversed list (step=-1) -> Output: [5, 4, 3, 2, 1]

# Modifying elements in the list
my_list[0] = 10               # Changing the first element to 10
print(my_list)                # Output: [10, 2, 3, 4, 5]

# Deleting an element
del my_list[1]                # Deleting the element at index 1 (which was 2)
print(my_list)                # Output: [10, 3, 4, 5]

# Inserting elements at a specific position
my_list[1:1] = [20, 30, 40]   # Inserting [20, 30, 40] at index 1 without replacing any elements
print(my_list)                # Output: [10, 20, 30, 40, 3, 4, 5]

1
5
3
[2, 3, 4]
[1, 2, 3]
[4, 5]
[1, 3, 5]
[5, 4, 3, 2, 1]
[10, 2, 3, 4, 5]
[10, 3, 4, 5]
[10, 20, 30, 40, 3, 4, 5]


2. Slicing & Indexing in Arrays

In [11]:
# Creating a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Accessing elements using positive and negative indexing
print(my_array[0])                # First element (index 0) -> Output: 1
print(my_array[-1])               # Last element (negative index -1) -> Output: 5
print(my_array[2])                # Third element (index 2) -> Output: 3

# Slicing the array
print(my_array[1:4])              # Elements from index 1 to 3 (excluding index 4) -> Output: [2, 3, 4]
print(my_array[:3])               # First 3 elements (index 0 to 2) -> Output: [1, 2, 3]
print(my_array[3:])               # Elements from index 3 to the end -> Output: [4, 5]
print(my_array[::2])              # Every second element (step=2) -> Output: [1, 3, 5]
print(my_array[::-1])             # Reversed array (step=-1) -> Output: [5, 4, 3, 2, 1]

# Modifying elements in the NumPy array
my_array[0] = 10                  # Changing the first element to 10
print(my_array)                   # Output: [10, 2, 3, 4, 5]

# Deleting an element (but doesn't modify the original array)
np.delete(my_array, 1)            # Deletes element at index 1 (which is 2)
print(my_array)                   # Output is still [10, 2, 3, 4, 5] because np.delete() returns a new array

# Inserting elements (but doesn't modify the original array)
np.insert(my_array, 1, [20, 30])  # Inserts 20 and 30 at index 1
print(my_array)                   # Output is still [10, 2, 3, 4, 5] because np.insert() returns a new array

1
5
3
[2 3 4]
[1 2 3]
[4 5]
[1 3 5]
[5 4 3 2 1]
[10  2  3  4  5]
[10  2  3  4  5]
[10  2  3  4  5]
