In [1]:
import numpy as np

1. Creating Fixed Size Arrays:

1.1 Zeros

In [2]:
zeros_array = np.zeros(10)
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3), dtype = int)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----
[[0 0 0]
 [0 0 0]]


1.2 Ones

In [3]:
ones_array = np.ones(10)
print(ones_array)
print('-----')

ones_array = np.ones((2, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3), dtype = int)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
-----
[[1 1 1]
 [1 1 1]]


1.3 Eye

In [6]:
eye_array = np.eye(3)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4)
print(eye_array)
print('-----')

eye_array = np.eye(5, 5, dtype = int)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


2. Random Number Generation:

2.1 Generating Random Numbers

In [16]:
print(np.random.rand())
print('-' * 10)

print(np.random.rand(10))
print('-' * 10)

print(np.random.rand(3, 3))
print('-' * 10)

print(np.random.randint(100))
print('-' * 10)

print(np.random.randint(100, size=10))
print('-' * 10)

print(np.random.randint(100, size=(3, 3)))
print('-' * 10)

print(np.random.randint(low=100, high=200, size=(3, 3)))
print('-' * 10)

# Generate a random number from a normal distribution with mean 0 and standard deviation 1
print(np.random.randn())
print('-' * 10)

# Generate a 2D array of 3x3 random numbers from a uniform distribution between 0 and 1
print(np.random.uniform(size=(3, 3)))
print('-' * 10)

# Generate a 2D array of 3x3 random numbers from a binomial distribution with n=10 and p=0.5
print(np.random.binomial(10, 0.5, size=(3, 3)))
print('-' * 10)

print(np.random.poisson(size=(3,3)))
print('-' * 10)

print(np.random.exponential(scale = 1.0, size=(3, 3)))
print('-' * 10)

# Poisson ,Exponential, Gamma, Chi-squared, T-distribution, F-distribution Beta Log-normal Laplace

0.602827064989658
----------
[0.54681286 0.33292419 0.0066559  0.78632106 0.18398772 0.56879366
 0.68390324 0.27993443 0.56234409 0.12865325]
----------
[[0.03403186 0.62219826 0.43190063]
 [0.96949071 0.23670422 0.27091283]
 [0.2053071  0.79046224 0.95876066]]
----------
74
----------
[22 61 41 73  8 73 21  0 59 72]
----------
[[30 88  3]
 [49 15 10]
 [72 65 52]]
----------
[[147 140 141]
 [157 131 106]
 [101 158 146]]
----------
-0.44465835012421767
----------
[[0.03158885 0.4842715  0.08148573]
 [0.16872715 0.61455834 0.29918387]
 [0.30406079 0.28174091 0.70724795]]
----------
[[6 5 5]
 [5 2 7]
 [4 6 6]]
----------
[[1 1 2]
 [0 1 1]
 [0 1 1]]
----------
[[1.59316127 1.10439103 0.14628025]
 [0.57119768 0.50228828 0.06208032]
 [1.57362373 0.12862141 2.32028937]]
----------
