In [2]:
import numpy as np

1. Generating Random Numbers:

In [6]:
print(np.random.rand())
print('-' * 10)

print(np.random.rand(3))
print('-' * 10)

print(np.random.randint(10))
print('-' * 10)

print(np.random.randint(10, size=(3, 5)))

0.5615798992259206
----------
[0.87910052 0.89130337 0.19335343]
----------
1
----------
[[9 0 7 4 9]
 [7 2 4 9 3]
 [0 8 4 0 2]]


2. Random numbers with Seed

In [8]:
np.random.seed(2)

print(np.random.rand())
print('-' * 10)

print(np.random.rand(3))
print('-' * 10)

print(np.random.randint(10))
print('-' * 10)

print(np.random.randint(10, size=(3, 5)))
print('-' * 10)

0.43599490214200376
----------
[0.02592623 0.54966248 0.43532239]
----------
8
----------
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]
----------


In [9]:
np.random.seed(5)

print(np.random.rand())
print('-' * 10)

print(np.random.rand(3))
print('-' * 10)

print(np.random.randint(10))
print('-' * 10)

print(np.random.randint(10, size=(3, 5)))
print('-' * 10)

0.22199317108973948
----------
[0.87073231 0.20671916 0.91861091]
----------
8
----------
[[4 7 0 0 7]
 [1 5 7 0 1]
 [4 6 2 9 9]]
----------


3. Seed in Loops:

In [10]:
np.random.seed(5)

# Run the loop 10 times
for i in range(10):

    # Generate an array of 1000 random integers (either 0 or 1)
    arr = np.random.randint(2, size=1000)

    # Count and print the number of ones and zeros in the array
    print(len(arr[arr == 1]), len(arr[arr == 0]))

505 495
509 491
481 519
508 492
510 490
490 510
503 497
475 525
496 504
499 501
