In [1]:
import numpy as np

1. Flattening

In [5]:
arr = np.array([[1, 2, 3],[ 4, 5, 6]])
print(arr)
print('-' * 10)

flat_arr = arr.flatten()
print(flat_arr)

[[1 2 3]
 [4 5 6]]
----------
[1 2 3 4 5 6]


2. Reshaping

In [7]:
arr = np.array([[1, 2, 3],[ 4, 5, 6]])
print(arr)
print('-' * 10)

reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
----------
[[1 2]
 [3 4]
 [5 6]]


3. Splitting

- vsplit

In [11]:
arr = np.array([[1, 2, 3],[ 4, 5, 6],[3, 5, 7],[1, 9, 8]])
print(arr)
print('-' * 10)

vs_split = np.vsplit(arr, 4)
print(vs_split)
print('-' * 10)

for i in np.vsplit(arr,4):
  print(i)

[[1 2 3]
 [4 5 6]
 [3 5 7]
 [1 9 8]]
----------
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[3, 5, 7]]), array([[1, 9, 8]])]
----------
[[1 2 3]]
[[4 5 6]]
[[3 5 7]]
[[1 9 8]]


- hsplit

In [16]:
arr = np.array([[1, 6, 2, 3],[ 4, 1, 5, 6],[3, 2, 5, 7],[1, 4, 9, 8]])
print(arr)
print('-' * 10)

hs_split = np.hsplit(arr, 4)
print(hs_split)
print('-' * 10)

for i in np.hsplit(arr,2):
  print(i)

[[1 6 2 3]
 [4 1 5 6]
 [3 2 5 7]
 [1 4 9 8]]
----------
[array([[1],
       [4],
       [3],
       [1]]), array([[6],
       [1],
       [2],
       [4]]), array([[2],
       [5],
       [5],
       [9]]), array([[3],
       [6],
       [7],
       [8]])]
----------
[[1 6]
 [4 1]
 [3 2]
 [1 4]]
[[2 3]
 [5 6]
 [5 7]
 [9 8]]


- Split

In [19]:
arr = np.array([[1, 6, 2, 3],[ 4, 1, 5, 6],[3, 2, 5, 7],[1, 4, 9, 8]])
print(arr)
print('-' * 10)

split = np.split(arr, 4 , axis = 0)       # prints horizontal value
print(split)
print('-' * 10)

for i in np.split(arr,4 , axis = 1):      # prints vertical value
  print(i)

[[1 6 2 3]
 [4 1 5 6]
 [3 2 5 7]
 [1 4 9 8]]
----------
[array([[1, 6, 2, 3]]), array([[4, 1, 5, 6]]), array([[3, 2, 5, 7]]), array([[1, 4, 9, 8]])]
----------
[[1]
 [4]
 [3]
 [1]]
[[6]
 [1]
 [2]
 [4]]
[[2]
 [5]
 [5]
 [9]]
[[3]
 [6]
 [7]
 [8]]


4. Merging

In [22]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 2, 7, 4])
arr3 = np.array([1, 6, 1, 7])
arr4 = np.array([4, 5, 4, 9])

concat_arr = np.concatenate((arr1, arr2, arr3, arr4))
print(concat_arr)

[1 2 3 4 5 2 7 4 1 6 1 7 4 5 4 9]


- hstack

In [23]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 2, 7, 4])
arr3 = np.array([1, 6, 1, 7])
arr4 = np.array([4, 5, 4, 9])

h_stack = np.hstack((arr1, arr2, arr3, arr4))
print(h_stack)

[1 2 3 4 5 2 7 4 1 6 1 7 4 5 4 9]


- vstack

In [24]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 2, 7, 4])
arr3 = np.array([1, 6, 1, 7])
arr4 = np.array([4, 5, 4, 9])

v_stack = np.vstack((arr1, arr2, arr3, arr4))
print(v_stack)

[[1 2 3 4]
 [5 2 7 4]
 [1 6 1 7]
 [4 5 4 9]]


- stack

In [26]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 2, 7, 4])
arr3 = np.array([1, 6, 1, 7])
arr4 = np.array([4, 5, 4, 9])

_stack = np.stack((arr1, arr2, arr3, arr4), axis = 0)
print(_stack)

[[1 2 3 4]
 [5 2 7 4]
 [1 6 1 7]
 [4 5 4 9]]


In [27]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 2, 7, 4])
arr3 = np.array([1, 6, 1, 7])
arr4 = np.array([4, 5, 4, 9])

_stack = np.stack((arr1, arr2, arr3, arr4), axis = 1)
print(_stack)

[[1 5 1 4]
 [2 2 6 5]
 [3 7 1 4]
 [4 4 7 9]]
