In [1]:
import numpy as np

In [ ]:
## Determinant----

In [2]:
A = np.array([[1,2],[3,4]])
determinant = np.linalg.det(A)
print(determinant)

-2.0000000000000004


In [5]:
B = np.array([[1,2,3], [4,5,6], [6,8,9]])
determinant = np.linalg.det(B)
print(determinant)

2.999999999999999


In [ ]:
## Transpose----

In [6]:
B = np.array([[1,2,3], [4,5,6], [7,8,9]])
Transpose = np.transpose(B)
print(Transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
C = np.array([[1,2,3],[4,5,6]])
Transpose = np.transpose(C)
print(Transpose)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
## Identity Matrix = Main diagonal is 1 and other elements are 0

In [ ]:
## Inverse----

In [8]:
A = np.array([[1,2],[3,4]])
Inverse = np.linalg.inv(A)
print(Inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]
