In [1]:
import numpy as np

In [ ]:
## Dot Product (Example)

In [2]:
a = np.array([1, 2])
b = np.array([2, 3])
dot_product = np.dot(a, b)
print("Dot Product:", dot_product)

Dot Product: 8


In [3]:
c = np.array([1, 2, 3])
d = np.array([2, 3, 4])
dot_product = np.dot(c, d)
print("Dot Product:", dot_product)

Dot Product: 20


In [4]:
x = np.array([1,2])
y = np.array([5,3])
dot_product = np.dot(x,y)
print("Dot Product:", dot_product)

Dot Product: 11


In [ ]:
## Matrix Multiplication (Example)

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])
product = np.matmul(A, B)
print("Matrix Product:\n", product)

Matrix Product:
 [[10 13]
 [22 29]]


In [6]:
C = np.array([1, 2])
D = np.array([[4, 1], [3, 5]])
product = np.matmul(C, D)
print("Broadcasted Matrix Product:\n", product)

Broadcasted Matrix Product:
 [10 11]


In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 3], [4, 5]])
product_dot = np.dot(A, B)
product_matmul = np.matmul(A, B)
print("Dot Product:\n", product_dot)
print("Matrix Multiplication:\n", product_matmul)

Dot Product:
 [[10 13]
 [22 29]]
Matrix Multiplication:
 [[10 13]
 [22 29]]
